const exercisesData = {
  1: {
    title: 'Ejercicio 1 - Hotels Along the Croatian Coast',
    icon: '/imagenes/hotel.png',
    description: 'Hay N hoteles a lo largo de la hermosa costa adriática. Cada hotel tiene su valor en Euros. Sroljo ha ganado M Euros en la lotería. Ahora quiere comprar una secuencia de hoteles consecutivos, de modo que la suma de los valores de estos hoteles consecutivos sea lo mayor posible, pero no mayor que M. Debe calcular este mayor valor total posible.',
    entrada: '(1 ≤ N ≤ 300 000, 1 ≤ M < 2^31). En la siguiente línea hay N números naturales menores que 10^6, que representan los valores del hotel en el orden en que se encuentran a lo largo de la costa.',
    salida: 'Imprima el número requerido (será mayor que 0 en todos los datos de la prueba).',
    template: 'https://onlinegdb.com/2cvIgn0t2',
    github: 'https://github.com/ImJGTorres/ejercicio-1-hotels-along-the-croatian-coast',
    pdf: '/Ejercicios/PDF/complejidad 1.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej1-hoteles_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej1-hoteles_solucion_codigo.pdf',
    visualization: true,
  },
  2: {
    title: 'Ejercicio 2 - Calculating Function',
    icon: '/imagenes/funcion.png',
    description: 'Para un entero positivo n definamos una función f:\nf(n) = - 1 + 2 - 3 + .. + (( - 1)^n)*n\nTu tarea es calcular f(n) para un entero dado n.',
    entrada: 'La única línea contiene el entero positivo n (1 ≤ n ≤ 10^15).',
    salida: 'Imprime f(n) en una sola línea.',
    template: 'https://onlinegdb.com/XPutClYlH',
    github: 'https://github.com/ImJGTorres/ejercicio-2-calculating-function',
    pdf: '/Ejercicios/PDF/complejidad 2.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej2-funcionCalculo_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej2-funcionCalculo_solucion_codigo.pdf',
    visualization: true,
  },
  3: {
    title: 'Ejercicio 3 - Favorite Sequence',
    icon: '/imagenes/secuencia.png',
    description: 'Policarpa tiene una secuencia favorita, la escribió en una pizarra de la siguiente manera:\n- Escribió el primer número a la izquierda.\n- El segundo número a la derecha.\n- El tercero lo más a la izquierda posible (pero después del primero).\n- El cuarto lo más a la derecha posible (pero antes del segundo).\n- Repite este proceso hasta escribir toda la secuencia.\n\nDada la secuencia final en la pizarra, reconstruye la secuencia original a.',
    entrada: 't (1 ≤ t ≤ 300) → número de casos de prueba.\nPara cada caso de prueba:\nn (1 ≤ n ≤ 300) → longitud de la secuencia.\nb₁,b₂,...,bₙ (1≤bᵢ≤10⁹) → secuencia escrita en la pizarra.',
    salida: 'Secuencia a que Policarpa escribió en la pizarra.',
    template: 'https://onlinegdb.com/_9iY7oHwc',
    github: 'https://github.com/ImJGTorres/ejercicio-3-secuencia-favorita',
    pdf: '/Ejercicios/PDF/complejidad 3.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej3-secuenciaFavorita_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej3-secuenciaFavorita_solucion_codigo.pdf',
    visualization: true,
  },
  4: {
    title: 'Ejercicio 4 - 2^Sort',
    icon: '/imagenes/ordenado.png',
    description: 'Dado un arreglo a de longitud n y un entero k, hallar el número de índices 1≤i≤n-k tales que la submatriz [aᵢ,...,aᵢ₊ₖ] con longitud k+1 (no con longitud k) tiene la siguiente propiedad:\n\nSi se multiplica el primer elemento por 2⁰, el segundo elemento por 2¹, ..., y el (k+1) elemento por 2ᵏ, entonces este sub arreglo está ordenado en orden estrictamente creciente.\n\nMás formalmente, contar el número de índices 1≤i≤n-k tales que:\n2⁰·aᵢ < 2¹·aᵢ₊₁ < 2²·aᵢ₊₂ < ⋯ < 2ᵏ·aᵢ₊ₖ',
    entrada: 'La primera línea contiene dos enteros, n y k (3 ≤ n ≤ 2·10⁵, 1 ≤ k < n), la longitud del arreglo y el número de desigualdades.\nLa segunda línea contiene n enteros a₁, a₂,...,aₙ (1 ≤ aᵢ ≤ 10⁹), los cuales representan los elementos del arreglo.',
    salida: 'Para cada caso de prueba, imprimir un solo entero, el numero de indices que satisfagan la condición del enunciado.',
    template: 'https://onlinegdb.com/TocKJMJt2',
    github: 'https://github.com/ImJGTorres/ejercicio-4-2sort',
    pdf: '/Ejercicios/PDF/complejidad 4.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej4-2Sorted_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej4-2Sorted_solucion_codigo.pdf',
    visualization: true,
  },
  5: {
    title: 'Ejercicio 5 - Walk on a multiplication table',
    icon: '/imagenes/multiplicar.png',
    description: 'Takahashi is standing on a multiplication table with infinitely many rows and columns. The square (i,j) contains the integer i×j. Initially, Takahashi is standing at (1,1). In one move, he can move from (i,j) to either (i+1,j) or (i,j+1).\n\nGiven an integer N, find the minimum number of moves needed to reach a square that contains N.',
    entrada: 'Input is given from Standard Input.\nN (2 ≤ N ≤ 10¹²)',
    salida: 'Print the minimum number of moves needed to reach a square that contains the integer N.',
    template: 'https://onlinegdb.com/6_PIUQmqz',
    github: 'https://github.com/ImJGTorres/ejercicio-5-walk-on-a-multiplication-table',
    pdf: '/Ejercicios/PDF/complejidad 5.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej5-multiplicationTable_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej5-multiplicationTable_solucion_codigo.pdf',
    visualization: true,
  },
  6: {
    title: 'Ejercicio 6 - Vlad and a Sum of Digits',
    icon: '/imagenes/suma.png',
    description: 'Vladislav escribe en la pizarra los números enteros del 1 al n, ambos inclusive. Después sustituye cada número entero por la suma de sus cifras. ¿Cuál es ahora la suma de los números del tablero?\n\nPor ejemplo, si n=12 entonces inicialmente los números del tablero son: 1,2,3,4,5,6,7,8,9,10,11,12.\nDespués de la sustitución, los números pasan a ser: 1,2,3,4,5,6,7,8,9,1,2,3.\nLa suma de estos números es 1+2+3+4+5+6+7+8+9+1+2+3=51.\nPor lo tanto, para n=12 la respuesta es 51.',
    entrada: 'La primera línea contiene un número entero t (1≤t≤10⁴) - el número de casos de prueba.\nLa única línea de cada caso de prueba contiene un único entero n (1≤n≤2⋅10⁵) - el mayor número que escribe Vladislav.',
    salida: 'Para cada caso de prueba, salida de un solo número entero - la suma de los números al final del proceso.',
    template: 'https://onlinegdb.com/ei8xxNASW',
    github: 'https://github.com/ImJGTorres/ejercicio-6-vlad-and-a-sum-of-digits',
    pdf: '/Ejercicios/PDF/complejidad 6.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej6-vladSum_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej6-vladSum_solucion_codigo.pdf',
    visualization: true,
  },
  7: {
    title: 'Ejercicio 7 - Simple Repetition',
    icon: '/imagenes/repeticion.png',
    description: '¡A Pasha le encantan los números primos! Una vez más, en sus intentos por encontrar una nueva forma de generar números primos, se interesó por un algoritmo que encontró en Internet:\n\nPara obtener un nuevo número y, repite k veces la representación decimal del número x (sin ceros a la izquierda).\n\nPor ejemplo:\n- Para x=52 y k=3, obtenemos y=525252\n- Para x=6 y k=7, obtenemos y=6666666666\n\nPasha realmente quiere que el número resultante y sea primo, pero aún no sabe cómo comprobar la primalidad de los números generados por este algoritmo. ¡Ayuda a Pasha y dile si y es primo!',
    entrada: 'La primera y única línea de cada conjunto de datos contiene dos enteros: x y k (1≤x≤10⁹, 1≤k≤7).',
    salida: 'Para cada conjunto de datos de entrada, indique «SÍ» (sin comillas) si el número resultante y será primo, y «NO» en caso contrario.',
    template: 'https://onlinegdb.com/QFlcrYfV1',
    github: 'https://github.com/ImJGTorres/ejercicio-7-simple-repetition',
    pdf: '/Ejercicios/PDF/complejidad 7.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej7-simpleRepetition_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej7-simpleRepetition_solucion_codigo.pdf',
    visualization: true,
  },
  8: {
    title: 'Ejercicio 8 - Diverse Team',
    icon: '/imagenes/team.png',
    description: 'Hay n alumnos en una clase escolar, la calificación del alumno i-ésimo en Codehorses es aᵢ.\n\nDebes formar un equipo compuesto por k alumnos (1≤k≤n) de tal manera que las calificaciones de todos los miembros del equipo sean distintas.\n\nSi es imposible formar un equipo adecuado, imprime «NO» (sin comillas). De lo contrario, imprime «SÍ» y, a continuación, imprime k números distintos que deben ser los índices de los alumnos del equipo que formes. Si hay varias respuestas, imprime cualquiera de ellas.',
    entrada: 'La primera línea contiene dos números enteros n y k (1≤k≤n≤10⁸): el número de estudiantes y el tamaño del equipo que debes formar.\nLa segunda línea contiene n números enteros a₁, a₂, ..., aₙ (1≤aᵢ≤10⁴), donde aᵢ es la calificación del estudiante i-ésimo.',
    salida: 'Si es imposible formar un equipo adecuado, imprime «NO» (sin comillas). De lo contrario, imprime «YES» y, a continuación, imprime k números enteros distintos del 1 al n, que deben ser los índices de los estudiantes del equipo que formes. Todas las calificaciones de los estudiantes del equipo deben ser distintas. Puedes imprimir los índices en cualquier orden. Si hay varias respuestas, imprime cualquiera de ellas.',
    template: 'https://onlinegdb.com/rEFLOyYVGC',
    github: 'https://github.com/ImJGTorres/ejercicio-8-diverseteam',
    pdf: '/Ejercicios/PDF/complejidad 8.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej8-diverseTeam_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej8-diverseTeam_solucion_codigo.pdf',
    visualization: true,
  },
  9: {
    title: 'Ejercicio 9 - Worms',
    icon: '/imagenes/gusano.png',
    description: 'Es la hora de comer para Topo. Su amigo, Marmota, le ha preparado un bonito juego para comer.\n\nMarmota le ha traído a Topo n montones ordenados de gusanos, de modo que el i-ésimo montón contiene aᵢ gusanos. Etiquetó todos estos gusanos con números enteros consecutivos:\n- Los gusanos del primer montón están etiquetados con los números del 1 al a₁\n- Los gusanos del segundo montón están etiquetados con los números del a₁ + 1 al a₁ + a₂\n- Y así sucesivamente.\n\nTopo no puede comerse todos los gusanos y, como todos sabemos, Topo es ciego, así que Marmota le dice las etiquetas de los gusanos más jugosos. Marmota sólo le dará un gusano a Topo si éste dice correctamente en qué montón se encuentra dicho gusano.',
    entrada: 'La primera línea contiene un único entero n (1 ≤ n ≤ 10⁵), el número de montones.\nLa segunda línea contiene n enteros a₁, a₂, ..., aₙ (1 ≤ aᵢ ≤ 10³, a₁ + a₂ + ... + aₙ ≤ 10⁶), donde aᵢ es el número de gusanos en la i-ésima pila.\nLa tercera línea contiene un único entero m (1 ≤ m ≤ 10⁵), el número de gusanos jugosos dicho por Marmota.\nLa cuarta línea contiene m enteros q₁, q₂, ..., qₘ, las etiquetas de los gusanos jugosos.',
    salida: 'Imprime m líneas en la salida estándar. La i-ésima línea debe contener un número entero, que representa el número de la pila donde está el gusano etiquetado con el número qᵢ.',
    template: 'https://onlinegdb.com/YuXPnpnuy',
    github: 'https://github.com/ImJGTorres/ejercicio-9-worms',
    pdf: '/Ejercicios/PDF/complejidad 9.pdf',
    pdfExplicacion: '/Ejercicios/PDF/Ej9-worms_explicacion.pdf',
    pdfSolucion: '/Ejercicios/PDF/Ej9-worms_solucion_codigo.pdf',
    visualization: true,
  },
};

export default exercisesData;
